[package]
name = "pvm-linker-bug-repro"
version = "0.1.0"
edition = "2021"

[dependencies]
polkavm-linker = "0.10"
revive-runner = { git = "https://github.com/xermicus/revive", branch = "pvm-link-bug" }
