[package]
name = "pvm-linker-bug-repro"
version = "0.1.0"
edition = "2021"

[dependencies]
#polkavm-linker = "0.10"
polkavm-linker = { path = "../polkavm/crates/polkavm-linker" }
revive-runner = { git = "https://github.com/xermicus/revive", branch = "pvm-link-bug" }
